### ISSUE TITLE
Java Server: UnsupportedOperationException when multiple players are connected to the server

### ISSUE THREAD

**Issue by fingerprince** [HL2-Ghosting-Team/src#5]
Was messing around with the Java based server earlier and found it breaking whenever a second player joined. Error is as follows: 

Adding user Taggart !
Exception in thread "Thread-1" java.lang.UnsupportedOperationException
        at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
        at GhostingServer$User.completeEvents(GhostingServer.java:643)
        at GhostingServer$ServerSend.run(GhostingServer.java:292)

My Java's crap, but I think the program is calling CopyOnWriteArrayList.remove() with no args, which is undefined, when the intention of the program is to call .remove() on the iterator object itself? Sorry if that's completely wrong, I have practically no experience with OOP.

I've managed to fix it be simply removing line 643 (iterator.remove();) which is probably just bad practice and ends up leaving stuff hanging around in memory, but works as a temporary fix.

Sorry if this seems a bit nick-picky, since there probably aren't many people that make any use of ghosting mod's server features, but it really is a great little server program and I'd love to see it working properly.

**Comment by Gocnak** [comment]
Aha, good catch. I forgot to update the removal after switching to a more concurrent friendly ArrayList. CopyOnWrite* classes' iterators do not support the remove() command. I've changed the loop and you can see how the new removal works.
